stages:
  - test
  - deploy

test:
  image: swamydev/geo-base:latest
  before_script:
    - ci/add-pypi-indices.sh ${PIP_EODC_R_ACCESS_TOKEN}
  script:
    - make test
  coverage: '/^TOTAL.+?(\d+\%)$/'

deploy:
  image: python:latest
  needs:
    - job: test
      artifacts: false
  script:
    - make dist
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
  artifacts:
    paths:
      - dist/*
    expire_in: 1 week
