name: Test with coverage

on: [ push, pull_request ]

jobs:
  test_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Test
        run: |
          git lfs install
          git lfs pull
          make test
          git lfs uninstall
          git push origin --delete python-coverage-comment
      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          VERBOSE: false